---
- name: spc
  hosts: all
  become: yes
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
    - name: url
      ansible.builtin.uri:
        url:  https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
        dest: /tmp/
        mode: "777"
    - name: Extract 
      ansible.builtin.unarchive:
        src: /tmp/
        dest: /opt/
        remote_src: yes


